= TeX-Converter
James Carlson
:numbered:
:toc2:
:stem: 

== Purpose

The aim of +tex-converter+ is to transform an asciidoc
document containing mathematics into a LaTeX document.
Two math formats are be supported, [blue]#asciimath#
and [blue]#LaTeX#. With them you can render expressions
such as stem:[ a^2 + b^2 = c^2 ] and

[stem]
++++
 e^{2\pi \sqrt{-1}} = 1
++++
(The above won't render properly on github right now, but
will render if this README is run through asciidoctor).


=== Asciimath syntax

Asciimath syntax is
as in the examples 
----
stem:[ a^2 + b^2 = c^2 ]
----

and

----
[stem]
++++
  e^{2\pi \sqrt{-1}} = 1
++++
----


The math content is written in LaTeX.
To activitate asciimath
processing, set [blue]#+:stem:+# or [blue]#+:stem: latexmath+#.  The

=== LaTeX syntax

Use the syntax as in the examples

----
$ a^2 + b^2 = c^2 $
----

and

----
\[ 
  e^{2\pi \sqrt{-1}} = 1 
\]
----


== Usage

The command

[source]
--
$ asciidoctor -r ./tex-converter.rb -b latex sample1.ad -o sample1.tex
--

will transform [blue]#+sample1.ad+# into the tex file  [blue]#+sample1.tex+#.
It can then be run through +pdflatex+. For a shortcut, use the 
included shell script [blue]#run#:

[source]
--
$ ./run sample1
-- 

For a more comple example with lots of math, 
see source file [blue]#+elliptic.ad+# in this repo.
The HTML is rendered at  http://epsilon.my.noteshare.io/notebook/195/?note=782[noteshare.io] --
compare this with the PDF rendered
via +tex-converter+.




== Files

=== Essential files

* tex-converter.rb -- transforms asciidoctor files to tex files
* tex_block.rb -- strips enclosing escaped braces as needed.
* preamble -- needed by tex-converter.rb
* macro -- could be empty, but at the moment is expected to be there.  The
file +elliptic.ad+ does use "macro"


=== Test files

* sample1.ad -- math in conventonal LaTeX form, +$ ... $+, etc.
* sample2.ad -- like sample1, but the mat is as in +stem:[a^ + b^2 = c^2]+, etc.
* elliptic.ad

One should use all three files in testing the code.

== Asciidoc Coverage

The following are handled by +tex-converter.rb+ at this
time.


. Sections through level 5

. Numbered and un-numbered lists.  Nesting has not
  been addressed
  
. Bold and italic text

. hyperlinks




== TeX Coverage and Issues


A construct like the equation environment,
----
    \[ 
	    \begin{equation} 
		... 
	    \end{equation} 
   \]
---- 
needs to be transformed to ----
---- 
	    \begin{equation} 
		... 
	    \end{equation} 
---- 
There is a tricky point here.  Environments
like the equation environment live outside
of the delimiters
----
\[
  ...
\]
----
But others live inside. The needed transformation
is given by +TeXBlock.process_environments+.  See
the file 'tex_block.rb' and the module therein. 


The TeXBlock package addresses the points made
above in the case of both convenctional LaTeX syntax
embedded in escaped braces and the +[stem]+ block
syntax.


=== Other TeX issues:


. The following symbols need to be passed through unchanged

** +--+
** +<+ 
** +>+
** +&+ -- important for typesettig matrices


. Some apostrophes and quotes are bad -- they get
translated as +&#1234;+ and TeX chokes on them.







