= TeX-Converter
James Carlson
:numbered:
:toc2:

== Purpose

The aim of +tex-converter+ is transform an asciidoc
document containing mathematics into a LaTeX document.
Several asciidoc formats will be supported:

* Asciidoc - use +:stem:+ or +:stem: latexmath+
* LaTeX - use the syntax
delmited by +$ ... $+ or by
----
      \[ ... \]
----
Currently the second format is supported (such as it is).
Support for the first is forthcoming (days, not weeks).


== Usage

The command

[source]
--
$ asciidoctor -r ./tex-converter.rb -b latex sample1.ad -o sample1.tex
--

will transform [blue]#+sample1.ad+# into the tex file  [blue]#+sample1.tex+#.
It can then be run through +pdflatex+. For a shortcut, use the 
included shell script [blue]#run#:

[source]
--
$ ./run sample1
-- 

For a more comple example with lots of math, 
see source file [blue]#+elliptic.ad+# in this repo.
The HTML is rendered at  http://epsilon.my.noteshare.io/notebook/195/?note=782[noteshare.io] --
compare this with the PDF rendered
via +tex-converter+.




== Files

=== Essential files

* tex-converter.rb -- transforms asciidoctor files to tex files
* tex_block.rb -- strips enclosing escaped braces as needed.
* preamble -- needed by tex-converter.rb
* macro -- could be empty, but at the moment is expected to be there.


=== Test files

* sample1.ad
* elliptic.ad

== Asciidoc Coverage

The following are handled by +tex-converter.rb+ at this
time.

. Sections through level 5

. Numbered and un-numbered lists.  Nesting has not
  been addressed
  
. Bold and italic text

. hyperlinks




== TeX Coverage and Issues


A construct like the equation environment,
----
    \[ 
	    \begin{equation} 
		... 
	    \end{equation} 
   \]
---- 
needs to be transformed to ----
---- 
	    \begin{equation} 
		... 
	    \end{equation} 
---- 
There is a tricky point here.  Environments
like the equation environment live outside
of the delimiters
----
\[
  ...
\]
----
But others live inside. The needed transformation
is given by +TeXBlock.process_environments+.  See
the file 'tex_block.rb' and the module therein. 





=== Other TeX issues:


. The following symbols need to be passed through unchanged

** +--+
** +<+ 
** +>+
** +&+ -- important for typesettig matrices


. Some apostrophes and quotes are bad -- they get
translated as +&#1234;+ and TeX chokes on them.







